id: ACBB89DCC
title: Prayer to Rigdzin Jigme Lingpa Invoking His Previous Incarnations
type: translation
pechas:
- IFA83D3A0
- I8A3D2B16
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:43:46.747805
  last_modified_at: 2023-01-04 12:43:46.747826
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  IFA83D3A0/E145: '9063'
  I8A3D2B16/47A6: '9063'
